### ISSUE TITLE
rocketscript breaks viewSwitcher

### ISSUE THREAD

**Issue by KevinGimbel** [Haroenv/cv#3]
Just notices that the "text/rocketscript" thing (from CloudFlare?) breaks the initActive of viewSwitcher. In other news, no view is activated by default. 

I've no idea why this is the case since the viewSwitcher Navigation still works.

**Comment by Haroenv** [comment]
Ai, that's bizarre, gotta either turn it off or fix it! Thanks for pointing this out!

**Comment by Haroenv** [comment]
seems solved now?

**Comment by KevinGimbel** [comment]
Still doesn't work here. 

Tested with Chrome v45.0.2454.101 (stable), Chrome v47.0.2522.1 (unstable) and Firefox 43 (Developer Edition) all on Ubuntu 14.04.

**Comment by Haroenv** [comment]
Bizarre, I don't seem to be able to make it not work anymore. Both on `https` as `http`

**Comment by KevinGimbel** [comment]
Seems it was a cache problem. I cleared all my browser caches and now it works fine!
